version: '3'
services:

  deluge:
    build: images/deluge/
    container_name: mboxdeluge
    hostname: deluge
    restart: unless-stopped
    tty: true
    ports:
    - 8112:8112
    volumes:
    - ./config/deluge:/config
    - ./config/flexget:/flexget

  plex:
    image: plexinc/pms-docker
    container_name: mboxplex
    hostname: plex
    restart: unless-stopped
    ports:
    - 32400:32400/tcp
    - 3005:3005/tcp
    - 8324:8324/tcp
    - 32469:32469/tcp
    - 1900:1900/udp
    - 32410:32410/udp
    - 32412:32412/udp
    - 32413:32413/udp
    - 32414:32414/udp
    #volumes:
    #- <path/to/plex/database>:/config
    #- <path/to/transcode/temp>:/transcode
    #- <path/to/media>:/data