version: '3'
services:

  torrent:
    build: images/torrent/
    container_name: mboxtorrent
    hostname: torrent
    restart: unless-stopped
    tty: true
    ports:
      - 9991:9091
      - 51413:51413/tcp
      - 51413:51413/udp
    volumes:
      - ./config/transmission:/transmission
      - ./config/flexget:/flexget
      - ./data/:/data

  plex:
    image: plexinc/pms-docker:plexpass
    container_name: mboxplex
    hostname: plex
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ./data:/data
      - plextemp:/transcode
      - plexconfig:/config

volumes:
  plexconfig:
  plextemp: