variables: variables.yml

templates:

  torrent:
    transmission:
      addpaused: no

  torrent-paused:
    transmission:
      addpaused: yes  

  tv:
    thetvdb_lookup: yes
    exists_series: 
      - '/media/tosh500/MediaLibrary/TVShows/{{series_name}}'
    transmission:
      path: /media/tosh500/Torrent/Completed/TVShows/{{series_name}}/Season {{series_season}}

  movies:
    imdb_lookup: yes
    seen_movies: strict
    exists:
      - '/media/tosh500/MediaLibrary/Movies'
    quality:
      - 720p webrip+
    imdb:
      min_score: 6.2
      min_votes: 2000
      min_year: 2016
      reject_genres:
        - horror
    transmission:
      path: /media/tosh500/Torrent/Completed/Movies/{{imdb_name}} ({{imdb_year}})

  notify:
    notify:
      entries:
        message: |+
          {% if imdb_name is defined %}
          *#New Movie*
          [{{imdb_name}} ({{imdb_year}})]({{imdb_url|d('')}})
          Score: {{imdb_score}}/10 - {{imdb_votes}} votes
          {% endif %}
          {% if tvdb_series_name is defined %}
          *#New Episode*
          {{tvdb_series_name}}
          S{{'%02d' % tvdb_season}}E{{'%02d' % tvdb_episode}}
          {% endif %}
        via:
          - telegram:
              bot_token: '{? telegram.bot.token ?}'
              parse_mode: markdown
              recipients:
                - username: '{? telegram.bot.recipient ?}'

tasks:

  showrss:
    rss: '{? feed.showrss ?}'
    all_series: yes
    template:
      - torrent
      - tv
      - notify

  yify:
    rss: https://yts.ag/rss/0/all/all/0
    quality:
      - 720p
    template:
      - torrent-paused
      - movies
      - notify

  shaanig:
    exec:
      on_start:
        phase: ~/bin/rss2flexget.py "https://www.shaanig.org/external.php?type=RSS2&forumids=30" /tmp/rss-shaanig.txt
    rss: file:///tmp/rss-shaanig.txt
    template:
      - torrent-paused
      - movies
      - notify

  mkvcage:
    exec:
      on_start:
        phase: ~/bin/rss2flexget.py "http://www.mkvcage.com/feed/" /tmp/rss-mkvcage.txt
    rss: file:///tmp/rss-mkvcage.txt
    template:
      - torrent-paused
      - movies
      - notify

